/* =====================================================================
   build.js — compiles content/*.md into assets/data/<phase>-data.js and
   keeps assets/data/phases-map.js in sync with the task lists.

   Run:  node content/tools/build.js             (all phases)
         node content/tools/build.js phase1      (single phase)
         node content/tools/build.js --check     (validate only, write nothing)

   Safety: refuses to write a phase that parses to zero tasks, and prints
   every warning the parser raised so nothing fails silently.
   ===================================================================== */
"use strict";

const fs = require("fs");
const path = require("path");
const { parsePhase } = require("./format.js");

const ROOT = path.resolve(__dirname, "..", "..");
const DATA_DIR = path.join(ROOT, "assets", "data");
const CONTENT_DIR = path.join(ROOT, "content");

const PHASES = ["essentials", "phase1", "phase2", "phase3", "phase4", "phase5", "phase6", "phase7", "phase8"];

const HEADER_NOTE = {
  essentials: "Section 0: Onboarding Essentials",
  phase1: "Phase 1: Basecamp", phase2: "Phase 2: Acclimation", phase3: "Phase 3: Ascent",
  phase4: "Phase 4: High Camp", phase5: "Phase 5: Summit Push", phase6: "Phase 6: Summit",
  phase7: "Phase 7: Expedition Lead", phase8: "Phase 8: Peak Certified"
};

const TRAILER = `
/* ---------------------------------------------------------------------------
   Learn-panel writing templates (convert IBM Docs -> readable prose).
   Source for all educational content: https://www.ibm.com/docs/en/maas360
   1. Metaphor:    Rewrite an IBM Docs paragraph as a 3-sentence everyday analogy.
   2. Bullet sum:  5 verb-first bullets a non-technical hire reads in <90s.
   3. Narrative:   Turn a step list into 2nd-person 'You click...' under 150 words.
   4. Concept:     Explain [concept] to someone new to enterprise software.
   5. Comparison:  A 2-column plain-language table contrasting [A] vs [B].
   --------------------------------------------------------------------------- */
`;

function varNameFor(phase) {
  return (phase === "essentials" ? "ESSENTIALS" : phase.toUpperCase()) + "_DATA";
}

// Emit the data object in the same shape/indentation the original files used.
function emitDataFile(phase, data) {
  const clean = {
    id: data.id,
    title: data.title,
    subtitle: data.subtitle,
    icon: data.icon,
    tasks: data.tasks.map(t => ({
      id: t.id,
      phaseId: t.phaseId || data.id,
      title: t.title,
      description: t.description,
      url: t.url,
      learn: t.learn.map(p => ({ id: p.id, title: p.title, body: p.body })),
      practice: Object.assign({ iframePlaceholder: t.practice.iframePlaceholder, steps: t.practice.steps }, t.practice.embedUrl ? { embedUrl: t.practice.embedUrl } : {}),
      assess: {
        questions: t.assess.questions.map(q =>
          q.type === "text"
            ? { type: "text", question: q.question }
            : { type: "mc", question: q.question, options: q.options, correct: q.correct })
      },
      apply: { isRealScenario: !!t.apply.isRealScenario, scenario: t.apply.scenario }
    }))
  };

  const head =
    `/* ${HEADER_NOTE[phase] || phase} — generated from content/${phase}.md by content/tools/build.js. */\n` +
    `/* Edit content/${phase}.md, then run: node content/tools/build.js */\n` +
    `/* IBM Docs reference: https://www.ibm.com/docs/en/maas360 */\n`;

  return head + `window.${varNameFor(phase)} = ` + JSON.stringify(clean, null, 2) + ";\n" + TRAILER;
}

function emitPhasesMap(allTasks) {
  let out = "/* phases-map.js — generated by content/tools/build.js. Lists all phases and task IDs */\n";
  out += "window.ALL_PHASES_MAP = {\n";
  const entries = PHASES.map(p => {
    const ids = (allTasks[p] || []).map(id => '    "' + id + '"').join(",\n");
    return '  "' + p + '": [\n' + ids + "\n  ]";
  });
  out += entries.join(",\n") + "\n};\n";
  return out;
}

function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes("--check");
  const only = args.filter(a => !a.startsWith("--"));
  const list = only.length ? only : PHASES;

  let totalTasks = 0, totalQ = 0, totalPanels = 0, totalWarn = 0, failed = 0;
  const allTasks = {};

  // Always parse every phase so phases-map.js stays complete.
  for (const phase of PHASES) {
    const mdFile = path.join(CONTENT_DIR, phase + ".md");
    if (!fs.existsSync(mdFile)) {
      console.log("MISS   content/" + phase + ".md not found — skipping");
      continue;
    }
    const data = parsePhase(fs.readFileSync(mdFile, "utf8"));
    allTasks[phase] = data.tasks.map(t => t.id);

    const q = data.tasks.reduce((n, t) => n + t.assess.questions.length, 0);
    const pn = data.tasks.reduce((n, t) => n + t.learn.length, 0);

    if (data.warnings.length) {
      console.log("\n" + phase + ".md — " + data.warnings.length + " warning(s):");
      data.warnings.forEach(w => console.log("   ! " + w));
      totalWarn += data.warnings.length;
    }

    if (!data.tasks.length) {
      console.log("ERROR  " + phase + ".md parsed to 0 tasks — refusing to write.");
      failed++;
      continue;
    }
    if (!data.id) {
      console.log("ERROR  " + phase + ".md has no '- id:' line — refusing to write.");
      failed++;
      continue;
    }

    totalTasks += data.tasks.length; totalQ += q; totalPanels += pn;

    if (list.includes(phase) && !checkOnly) {
      fs.writeFileSync(path.join(DATA_DIR, phase + "-data.js"), emitDataFile(phase, data), "utf8");
      console.log("BUILD  " + phase + "-data.js   " + data.tasks.length + " tasks, " + pn + " panels, " + q + " questions");
    } else {
      console.log("CHECK  " + phase + ".md        " + data.tasks.length + " tasks, " + pn + " panels, " + q + " questions");
    }
  }

  if (!checkOnly && !failed) {
    fs.writeFileSync(path.join(DATA_DIR, "phases-map.js"), emitPhasesMap(allTasks), "utf8");
    console.log("BUILD  phases-map.js");
  }

  console.log("\nTotals: " + totalTasks + " tasks, " + totalPanels + " learn panels, " + totalQ + " questions, " + totalWarn + " warnings.");
  if (failed) { console.log(failed + " phase(s) failed."); process.exitCode = 1; }
}

main();
